import { IRecursosVocabulario } from "../models/Administrador/RecursosVocabulario"
import { ICategoria } from '../models/Administrador/Categoria';
import { IPuzzle } from './Rompecabeza.Interface';
import { ICategory } from "./Categoria.interface";
import { IVocabulary } from './Vocabulario.Interface';

export interface IPieza {
    Rompecabeza:IPuzzle[];
    Categoria:ICategory[];
    Vocabulario:IJuego;
    
}

interface IJuego{
        juego1:IVocabulary[];
        juego2:IVocabulary[];
        juego3:IVocabulary[];
        juego4:IVocabulary[];
        juego5:IVocabulary[];
}


// Generated by https://quicktype.io

export interface IPrePartida {
    Rompecabeza: IPuzzle;
    Categoria:   ICategory[];
    Vocabulario: IVocabularioP;
}

export interface IVocabularioP {
    juego1: IJuegoV;
    juego2: IJuegoV;
    juego3: IJuegoV;
    juego4: IJuegoV;
    juego5: IJuegoV;
}

export interface IJuegoV {
    Palabra1: Palabra1Class;
    Palabra2: Palabra1Class;
    Palabra3: Palabra1Class;
}

export interface Palabra1Class {
    palabra:   IRecursosVocabulario;
    Imagen:    IRecursosVocabulario;
    Respuesta: IRecursosVocabulario;
}








