// Generated by https://quicktype.io

export interface MultiJugador {
    Grupos:    Grupos;
    Equipos:   Equipos;
    Fecha:     string[];
    _id:       string;
    createdAt: string;
    updatedAt: string;
}

export interface Equipos {
    equipo0: Grupo[];
    equipo1: Grupo[];
}

export interface Grupo {
    label: string;
    value: string;
}

export interface Grupos {
    equipo: Grupo[];
    grupo:  Grupo;
}
